# Generated by Django 5.2.7 on 2025-10-04 03:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('products', '0002_alter_product_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Miqdor')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narx')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Jami narx')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Chegirma (%)')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Yakuniy narx')),
                ('payment_method', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('transfer', "O'tkazma")], default='cash', max_length=10, verbose_name="To'lov usuli")),
                ('sale_date', models.DateTimeField(auto_now_add=True, verbose_name='Sotilgan sana')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.account', verbose_name='Mijoz')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Mahsulot')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Sotuvchi')),
            ],
            options={
                'verbose_name': 'Sotuv',
                'verbose_name_plural': 'Sotuvlar',
                'ordering': ['-sale_date'],
            },
        ),
    ]
