# Generated by Django 5.2.7 on 2025-10-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Mahsulot nomi')),
                ('brand', models.CharField(max_length=100, verbose_name='Brend')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narx')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Miqdor')),
                ('unit', models.CharField(choices=[('kg', 'Kilogramm'), ('dona', 'Dona'), ('kub', 'Kub'), ('litr', 'Litr'), ('metr', 'Metr')], max_length=10, verbose_name='Oʻlchov birligi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'unique_together': {('name', 'brand')},
            },
        ),
    ]
