# Generated by Django 5.2.7 on 2025-10-05 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Maydon nomi')),
                ('field_type', models.CharField(choices=[('text', 'Matn'), ('int', 'Butun son'), ('float', "O'nlik son"), ('date', 'Sana')], max_length=20, verbose_name='Maydon turi')),
                ('is_required', models.BooleanField(default=False, verbose_name='Majburiy')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Maxsus maydon',
                'verbose_name_plural': 'Maxsus maydonlar',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict, verbose_name="Qo'shimcha maydonlar"),
        ),
    ]
