# Generated by Django 5.2.7 on 2025-10-05 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_customfield_product_custom_fields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomField',
        ),
        migrations.RemoveField(
            model_name='product',
            name='custom_fields',
        ),
    ]
